### ISSUE TITLE
Borderlands not respond

### ISSUE THREAD

**Issue by fntq** [c0dycode/BL-CommandInjector#2] opened 2019-06-10 17:09 UTC
Hi, could you update CommandInjector-UHD, because if the plugin is installed. Borderlands does not respond after launcher. ty

**Comment by c0dycode** [comment] 2019-06-10 18:09
Originally I had planned that I will no longer update this and autoexec, but I guess I just can't let you and other people down like that. I'll work on an update :) ❤️

**Comment by fntq** [comment] 2019-06-10 18:17
ok, nice! ;) ty <3

**Comment by c0dycode** [comment] 2019-06-10 18:37
Give this version a try :)
[CommandInjector-UHD.zip](https://github.com/c0dycode/BL-CommandInjector/files/3273304/CommandInjector-UHD.zip)

**Comment by B4LINT** [comment] 2019-06-10 18:54
No crash for me, but the Commader not working, (thats the only Plugin I use) I guess its up to m0pi to fix it if thats the case.

**Comment by c0dycode** [comment] 2019-06-10 18:56
Can you double check with the Example Application that's bundled with the other CommandInjector archive that everything is installed correctly?

If both messages at the top are green, then try entereing
> say Testmessage

in the Textbox and then press the button and see if it's displayed in the in-game chat

**Comment by fntq** [comment] 2019-06-10 20:15
i have same problem, game run but borderlands commander don't work.

**Comment by B4LINT** [comment] 2019-06-10 20:21
The plugin loader is green, but the commandinjector is red https://imgur.com/w3uW7r6

**Comment by c0dycode** [comment] 2019-06-10 20:23
In that case, try installing this vc_resist :) https://aka.ms/vs/16/release/vc_redist.x86.exe

That has fixed this issue for some people before too. Can't hurt to try 👍

**Comment by c0dycode** [comment] 2019-06-10 21:15
Okay, I just got around to test it myself with Commander. The dll was loaded for me, but commander was not reacting. Seems to be fixed with this. :)

[CommandInjector-UHD.zip](https://github.com/c0dycode/BL-CommandInjector/files/3273821/CommandInjector-UHD.zip)

**Comment by fntq** [comment] 2019-06-10 21:23
yea, now it work. thank you so much.

**Comment by Judgy53** [comment] 2019-06-10 21:29
Works as well for me, both Example App and Commanders works as intended.

**Comment by c0dycode** [comment] 2019-06-10 21:31
Awesome :) Glad to hear that. Thanks for testing ❤️

**Closed** 2019-06-10 22:11 UTC
